sonar.projectKey=victron-venus_dbus-esphome-grid-sensor
sonar.organization=victron-venus

sonar.exclusions=.github/workflows/release.yml

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,**/conftest.py
sonar.cpd.exclusions=tests/**

sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S6444
sonar.issue.ignore.multicriteria.e1.resourceKey=.github/workflows/release.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S5843
sonar.issue.ignore.multicriteria.e2.resourceKey=.github/workflows/release.yml
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S5843
sonar.issue.ignore.multicriteria.e3.resourceKey=.github/workflows/release.yml